baseURL = "https://mutualaid.info"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mutualaid.info"
theme = "plague"

[frontmatter]
  date = [':filename', ':default']

[params]
  siteHeaderText = "mutualaid.info"
  siteFooterText = "Powered by [Hugo](https://gohugo.io/) and the [plague](https://github.com/brianreumere/plague) theme. Hosted on [OpenBSD](https://www.openbsd.org/) üê° by [CR Servers](https://www.crservers.com/green-hosting.html) üå±."

  showHcard = true

  [params.indieWeb]
    avatar = "images/avatar.jpg"
    fullName = "brian"
    pronouns = ['he', 'him', 'his']
    nickname = "brianreumere"
    city = "test"
    region = "test"
    country = "US"
    emailAddress = "brian@mutualaid.info"
    gitHubUsername = "brianreumere"
    twitterHandle = "brianreumere"
    showLocation = false
